<a href="https://colab.research.google.com/github/joanby/python-ml-course/blob/Collab---v-3.8/notebooks/T1%20-%202%20-%20Data%20Cleaning%20-%20Análisis%20Preliminar%20de%20los%20Datos-Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Resumen de los datos: dimensiones y estructuras

In [2]:
import pandas as pd
import os

In [3]:
mainpath = "/content/drive/MyDrive/Python Machine Learning JGG/datasets"
filename = "titanic/titanic3.csv"
fullpath = os.path.join(mainpath, filename)

urldata = "https://raw.githubusercontent.com/serbengut/machine_learning_JGG/master/datasets/titanic/titanic3.csv" # hay que dar a raw en github y poner esa url


In [76]:
data = pd.read_csv(urldata)

In [5]:
data.head(5)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [6]:
data.tail(8)

pclass  survived                       name     sex   age  sibsp  parch  \
1301       3         0       Youseff, Mr. Gerious    male  45.5      0      0   
1302       3         0          Yousif, Mr. Wazli    male   NaN      0      0   
1303       3         0      Yousseff, Mr. Gerious    male   NaN      0      0   
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1301    2628   7.2250   NaN        C  NaN  312.0       NaN  
1302    2647   7.2250   NaN        C  NaN    NaN       NaN  
1303    2627  14.4583   NaN        C  NaN    NaN       NaN  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [7]:
data.shape

(1309, 14)

In [8]:
data.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [9]:
data.columns.values

array(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype=object)

Vamos a hacer un resumen de los estadísticos básicos de las variables numéricas.

In [10]:
data.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [11]:
data.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

# Missing values

In [12]:
pd.isnull(data["body"])

0        True
1        True
2        True
3       False
4        True
        ...  
1304    False
1305     True
1306    False
1307     True
1308     True
Name: body, Length: 1309, dtype: bool

In [13]:
pd.notnull(data["body"])

0       False
1       False
2       False
3        True
4       False
        ...  
1304     True
1305    False
1306     True
1307    False
1308    False
Name: body, Length: 1309, dtype: bool

In [14]:
pd.isnull(data["body"]).values.ravel().sum()

1188

In [15]:
pd.notnull(data["body"]).values.ravel().sum()

121

In [16]:
### inciso ### ravel() y flatten()
# Tanto ravel() como flatten() sirven para **APLANAR** una matriz de datos y convertirla en una matriz de una dimensión o array. 
# Os dejo un ejemplo sencillo y la explicación de cada uno por si os sirve.
# tanto flatten como ravel 'aplanan' una matriz
import numpy as np
matriz = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(matriz)
print(matriz.flatten())
print(matriz.ravel())
matriz.flatten()[0]=100
print("matriz con flatten NO modifica original \n", matriz)
matriz.ravel()[0]=100
print("matriz con ravel SI modifica el original \n", matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
matriz con flatten NO modifica original 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matriz con ravel SI modifica el original 
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
# flatten(): Solo nos retornará una copia del array original, por lo que si modificamos su composición en el transcurso de nuestro código, nos seguirá devolviendo el array inicial.
# ravel(): Su resultado es una vista o referencia del array que esta aplanando o convirtiendo,pero si este cambia, al ser una referencia,el también se ve afectado y actualiza su contenido.

Los valores que faltan en un data set pueden venir por dos razones:
* Extracción de los datos (en la base de datos a lo mejor el formato no era el adecuado)
* Recolección de los datos (ej: en una encuesta alguien no contesta alguna pregunta por algún motivo)

#### Borrado de valores que faltan

In [17]:
# axis=0 borra la fila, axis=1 borra la columna; how="all" solo borra la fila si todos sus columnas son NaN, si how="any", borra la fila entera solo con que haya una columna con NaN
data.dropna(axis=0, how="all") 

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [18]:
data2 = data #hago una copia 

In [20]:
# axis=0 borra la fila, axis=1 borra la columna; how="all" solo borra la fila si todos sus columnas son NaN, si how="any", borra la fila entera solo con que haya una columna con NaN
# en este ejemplo perdemos todas las líneas porque en todas las líneas había al menos un valor NaN
data2.dropna(axis=0, how="any")

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

#### Cómputo de los valores fantantes

In [ ]:
# consiste en rellenar los datos que faltan con algún valor: 0, la media, un string....

In [21]:
data3 = data #hago una copia

In [22]:
data3.fillna(0) #rellenos los datos con 0

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S    0   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S    0   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S    0   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542        0        C    0   
1305  female   0.0000      1      0    2665   14.4542        0        C    0   
1306    male  26.5000      0      0    2656    7.2250        0        C    0   
1307    male  27.0000      0      0    2670    7.2250        0        C    0   
1308    male  29.0000      0      0  315082    7.8750        0        S    0   

       body                        home.dest  
0       0.0                     St Louis, MO  
1       0.0  Montreal, PQ / Chesterville, ON  
2       0.0  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       0.0  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                                0  
1305    0.0                                0  
1306  304.0                                0  
1307    0.0                                0  
1308    0.0                                0  

[1309 rows x 14 columns]

In [23]:
data4 = data

In [24]:
data4= data4.fillna("Desconocido") # relleno los datos con desconocido
data4

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex          age  sibsp  parch  ticket      fare        cabin  \
0     female         29.0      0      0   24160  211.3375           B5   
1       male       0.9167      1      2  113781    151.55      C22 C26   
2     female          2.0      1      2  113781    151.55      C22 C26   
3       male         30.0      1      2  113781    151.55      C22 C26   
4     female         25.0      1      2  113781    151.55      C22 C26   
...      ...          ...    ...    ...     ...       ...          ...   
1304  female         14.5      1      0    2665   14.4542  Desconocido   
1305  female  Desconocido      1      0    2665   14.4542  Desconocido   
1306    male         26.5      0      0    2656     7.225  Desconocido   
1307    male         27.0      0      0    2670     7.225  Desconocido   
1308    male         29.0      0      0  315082     7.875  Desconocido   

     embarked         boat         body                        home.dest  
0           S            2  Desconocido                     St Louis, MO  
1           S           11  Desconocido  Montreal, PQ / Chesterville, ON  
2           S  Desconocido  Desconocido  Montreal, PQ / Chesterville, ON  
3           S  Desconocido        135.0  Montreal, PQ / Chesterville, ON  
4           S  Desconocido  Desconocido  Montreal, PQ / Chesterville, ON  
...       ...          ...          ...                              ...  
1304        C  Desconocido        328.0                      Desconocido  
1305        C  Desconocido  Desconocido                      Desconocido  
1306        C  Desconocido        304.0                      Desconocido  
1307        C  Desconocido  Desconocido                      Desconocido  
1308        S  Desconocido  Desconocido                      Desconocido  

[1309 rows x 14 columns]

In [25]:
data5 = data

In [27]:
# rellenos los datos NaN de Body con 0 y los datos de home.dest con desconocido
data5["body"] = data5["body"].fillna(0)
data5["home.dest"] = data5["home.dest"].fillna("Desconocido")
data5.head(15)

pclass  survived                                               name  \
0        1         1                      Allen, Miss. Elisabeth Walton   
1        1         1                     Allison, Master. Hudson Trevor   
2        1         0                       Allison, Miss. Helen Loraine   
3        1         0               Allison, Mr. Hudson Joshua Creighton   
4        1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5        1         1                                Anderson, Mr. Harry   
6        1         1                  Andrews, Miss. Kornelia Theodosia   
7        1         0                             Andrews, Mr. Thomas Jr   
8        1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
9        1         0                            Artagaveytia, Mr. Ramon   
10       1         0                             Astor, Col. John Jacob   
11       1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
12       1         1                      Aubart, Mme. Leontine Pauline   
13       1         1                       Barber, Miss. Ellen "Nellie"   
14       1         1               Barkworth, Mr. Algernon Henry Wilson   

       sex      age  sibsp  parch    ticket      fare    cabin embarked boat  \
0   female  29.0000      0      0     24160  211.3375       B5        S    2   
1     male   0.9167      1      2    113781  151.5500  C22 C26        S   11   
2   female   2.0000      1      2    113781  151.5500  C22 C26        S  NaN   
3     male  30.0000      1      2    113781  151.5500  C22 C26        S  NaN   
4   female  25.0000      1      2    113781  151.5500  C22 C26        S  NaN   
5     male  48.0000      0      0     19952   26.5500      E12        S    3   
6   female  63.0000      1      0     13502   77.9583       D7        S   10   
7     male  39.0000      0      0    112050    0.0000      A36        S  NaN   
8   female  53.0000      2      0     11769   51.4792     C101        S    D   
9     male  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   
10    male  47.0000      1      0  PC 17757  227.5250  C62 C64        C  NaN   
11  female  18.0000      1      0  PC 17757  227.5250  C62 C64        C    4   
12  female  24.0000      0      0  PC 17477   69.3000      B35        C    9   
13  female  26.0000      0      0     19877   78.8500      NaN        S    6   
14    male  80.0000      0      0     27042   30.0000      A23        S    B   

     body                        home.dest  
0     0.0                     St Louis, MO  
1     0.0  Montreal, PQ / Chesterville, ON  
2     0.0  Montreal, PQ / Chesterville, ON  
3   135.0  Montreal, PQ / Chesterville, ON  
4     0.0  Montreal, PQ / Chesterville, ON  
5     0.0                     New York, NY  
6     0.0                       Hudson, NY  
7     0.0                      Belfast, NI  
8     0.0              Bayside, Queens, NY  
9    22.0              Montevideo, Uruguay  
10  124.0                     New York, NY  
11    0.0                     New York, NY  
12    0.0                    Paris, France  
13    0.0                      Desconocido  
14    0.0                    Hessle, Yorks

In [29]:
pd.isnull(data5["age"]).values.ravel().sum() # me dice cuántos vacios hay en la columna age

263

In [30]:
data5["age"].fillna(data["age"].mean()) # rellenos los datos vacíos de la columna age con la media (mean)

0       29.000000
1        0.916700
2        2.000000
3       30.000000
4       25.000000
          ...    
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1309, dtype: float64

In [33]:
data5["age"][1305] #para comprobar que el valor del 1305 era NaN

nan

In [36]:
data5["age"].fillna(method="ffill") # rellena el NaN con el valor existente antes (en este caso el primer valor existente antes del 1305 era el 1304 que valía 14.5)

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...   
1304    14.5000
1305    14.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [37]:
data5["age"].fillna(method="backfill") # rellena el NaN con el valor existente después (en este caso el primer valor existente despues del 1305 era el 1306 que valía 26.5)

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...   
1304    14.5000
1305    26.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

# Variables dummy

In [ ]:
# defino tantas nuevas categorías como distintas variables tenga. en este caso, en sex tengo male y female, 
#por lo tanto hago dos nuevas columnas dandoles valor 1 o 0 según corresponda

In [67]:
data["sex"].head(10)

0    female
1      male
2    female
3      male
4    female
5      male
6    female
7      male
8    female
9      male
Name: sex, dtype: object

In [68]:
dummy_sex = pd.get_dummies(data["sex"], prefix="sex") #creamos una columna/s donde el prefijo es "sex" seguido de barra baja y male o female

In [69]:
dummy_sex.head(10)

sex_female  sex_male
0           1         0
1           0         1
2           1         0
3           0         1
4           1         0
5           0         1
6           1         0
7           0         1
8           1         0
9           0         1

In [70]:
column_name=data.columns.values.tolist()
column_name

['pclass',
 'survived',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'cabin',
 'embarked',
 'boat',
 'body',
 'home.dest']

In [71]:
data6 = data.drop(["sex"], axis = 1)
data6

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 13 columns]

In [72]:
data6 = pd.concat([data, dummy_sex], axis = 1)
data6

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  sex_female  sex_male  
0       NaN                     St Louis, MO           1         0  
1       NaN  Montreal, PQ / Chesterville, ON           0         1  
2       NaN  Montreal, PQ / Chesterville, ON           1         0  
3     135.0  Montreal, PQ / Chesterville, ON           0         1  
4       NaN  Montreal, PQ / Chesterville, ON           1         0  
...     ...                              ...         ...       ...  
1304  328.0                              NaN           1         0  
1305    NaN                              NaN           1         0  
1306  304.0                              NaN           0         1  
1307    NaN                              NaN           0         1  
1308    NaN                              NaN           0         1  

[1309 rows x 16 columns]

In [77]:
def createDummies(df, var_name):
    dummy = pd.get_dummies(df[var_name], prefix=var_name)
    df = df.drop(var_name, axis = 1)
    df = pd.concat([df, dummy ], axis = 1)
    return df

In [75]:
createDummies(data3, "sex")

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    0.0   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    0.0   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    0.0   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    0.0   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    0.0   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    0.0   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    0.0   

                            home.dest  sex_female  sex_male  
0                        St Louis, MO           1         0  
1     Montreal, PQ / Chesterville, ON           0         1  
2     Montreal, PQ / Chesterville, ON           1         0  
3     Montreal, PQ / Chesterville, ON           0         1  
4     Montreal, PQ / Chesterville, ON           1         0  
...                               ...         ...       ...  
1304                      Desconocido           1         0  
1305                      Desconocido           1         0  
1306                      Desconocido           0         1  
1307                      Desconocido           0         1  
1308                      Desconocido           0         1  

[1309 rows x 15 columns]

In [47]:
# creo variables dummy por mi cuenta:
dummy_class = pd.get_dummies(data["pclass"], prefix="Class")

In [52]:
dummy_class.head()

Class_1  Class_2  Class_3
0        1        0        0
1        1        0        0
2        1        0        0
3        1        0        0
4        1        0        0

In [80]:
data7=createDummies(data3, "pclass")

In [81]:
createDummies(data7, "sex")

survived                                             name      age  \
0            1                    Allen, Miss. Elisabeth Walton  29.0000   
1            1                   Allison, Master. Hudson Trevor   0.9167   
2            0                     Allison, Miss. Helen Loraine   2.0000   
3            0             Allison, Mr. Hudson Joshua Creighton  30.0000   
4            0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000   
...        ...                                              ...      ...   
1304         0                             Zabour, Miss. Hileni  14.5000   
1305         0                            Zabour, Miss. Thamine      NaN   
1306         0                        Zakarian, Mr. Mapriededer  26.5000   
1307         0                              Zakarian, Mr. Ortin  27.0000   
1308         0                               Zimmerman, Mr. Leo  29.0000   

      sibsp  parch  ticket      fare    cabin embarked boat   body  \
0         0      0   24160  211.3375       B5        S    2    0.0   
1         1      2  113781  151.5500  C22 C26        S   11    0.0   
2         1      2  113781  151.5500  C22 C26        S  NaN    0.0   
3         1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4         1      2  113781  151.5500  C22 C26        S  NaN    0.0   
...     ...    ...     ...       ...      ...      ...  ...    ...   
1304      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      1      0    2665   14.4542      NaN        C  NaN    0.0   
1306      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307      0      0    2670    7.2250      NaN        C  NaN    0.0   
1308      0      0  315082    7.8750      NaN        S  NaN    0.0   

                            home.dest  pclass_1  pclass_2  pclass_3  \
0                        St Louis, MO         1         0         0   
1     Montreal, PQ / Chesterville, ON         1         0         0   
2     Montreal, PQ / Chesterville, ON         1         0         0   
3     Montreal, PQ / Chesterville, ON         1         0         0   
4     Montreal, PQ / Chesterville, ON         1         0         0   
...                               ...       ...       ...       ...   
1304                      Desconocido         0         0         1   
1305                      Desconocido         0         0         1   
1306                      Desconocido         0         0         1   
1307                      Desconocido         0         0         1   
1308                      Desconocido         0         0         1   

      sex_female  sex_male  
0              1         0  
1              0         1  
2              1         0  
3              0         1  
4              1         0  
...          ...       ...  
1304           1         0  
1305           1         0  
1306           0         1  
1307           0         1  
1308           0         1  

[1309 rows x 17 columns]