In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

## OJO

En la versión 3.9 de python, al menos a la fecha la función sklearn.feature_selection  RFE ha sufrido un cambio en el segundo parámetro que genera un fallo, pasa de
RFE(estimator,  2, step=1)
a
RFE(estimator,  n_features_to_select=2, step=1)
para que funcione correctamente.

In [ ]:
# RFE: recursive feature elimination. es similar a eliminar cada vez una variable. simplemente le tenemos que decir cuántas variables queremos tener. él solo va poniendo y 
# quitando hasta quedarse con el número de vbles que le hemos indicado

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Python Machine Learning JGG/datasets/ads/Advertising.csv")

In [4]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [14]:
# nombro las columnas de predicción:

feature_cols = ["TV", "Radio", "Newspaper"]

In [15]:
# separo en dos datasets:
# X: el que se lleva las vbles candidatas a vbles. predictoras
# Y: la vble predecida

X = data[feature_cols]
Y = data["Sales"]

In [16]:
estimator = SVR(kernel="linear") # dentro de RFE usamos lineal
selector = RFE(estimator, n_features_to_select=2, step=1) # el 2 significa que quiero quedarme con dos vbles predictoras; el step=1 es para que lo haga en un paso
selector = selector.fit(X,Y)

In [17]:
# para ver la lista de las vbles con las que nos hemos quedado:

selector.support_

array([ True,  True, False])

In [18]:
# es decir, nos hemos quedadto con TV, Radio (true) y descartamos Newspaper (false)
# esto concluye, que la selección de variables que hicmos en el colab antes tiene sentido, ya que coincide con esto.

# también podemos pedirle un ranking de vbles:

In [19]:
selector.ranking_

array([1, 1, 2])

In [ ]:
# 1: significa que nos quedamos con ella (es más significativa que las de rango 2)
# 2: a medida que aumenta el rango, van perdiendo más significidad

In [ ]:
# ahora podemos hallar el modelo, o bien como se hizo en el colab anterior, o con scikit-learn:

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
X_pred = X[["TV", "Radio"]]

In [22]:
lm = LinearRegression()
lm.fit(X_pred,Y)

LinearRegression()

In [23]:
lm.intercept_ # nos da la alfa

2.9210999124051362

In [24]:
lm.coef_ # nos da los coeficientes que van con TV y Radio

array([0.04575482, 0.18799423])

In [27]:
lm.score(X_pred,Y) # nos da R2

0.8971942610828957