In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3) # saco 90 números aleatorios entre 0 y 1 y los reorganizo en 30 listas de 3 elementos cada una
data

array([[0.11128079, 0.14820854, 0.96757639],
       [0.24377467, 0.46063174, 0.16711776],
       [0.24829205, 0.89786738, 0.51411878],
       [0.02194194, 0.92851212, 0.24524337],
       [0.59923155, 0.46389489, 0.49445366],
       [0.90200845, 0.64293097, 0.30510594],
       [0.51879664, 0.36662159, 0.1907628 ],
       [0.70589487, 0.54084914, 0.20820714],
       [0.61004416, 0.71063197, 0.05611503],
       [0.40833394, 0.15426176, 0.28525938],
       [0.45603277, 0.19025929, 0.89335555],
       [0.17945017, 0.08280462, 0.71189481],
       [0.06516592, 0.35774603, 0.52548042],
       [0.40108961, 0.70397365, 0.21945707],
       [0.81564895, 0.41468751, 0.48186808],
       [0.60197792, 0.03248573, 0.57575588],
       [0.79286393, 0.01786208, 0.35923338],
       [0.12890006, 0.64616895, 0.56964353],
       [0.11748532, 0.24816601, 0.22320726],
       [0.41465529, 0.43978066, 0.77644236],
       [0.48351903, 0.87258836, 0.95944615],
       [0.97404583, 0.60472404, 0.96031738],
       [0.

In [ ]:
# recordamos que k-means tiene el problema de saber cuántos k hemos de tener
# entonces imaginamos que el analista, o el experto en markéting, decide que k=2
# seleccionamos dos obsesrvaciones al azar y esos serán los dos baricentros

In [3]:
c1 = np.random.choice(range(len(data))) # elijo aleatoriamente un punto
c2 = np.random.choice(range(len(data))) # elijo aleatoriamente otro punto
clust_centers = ([data[c1], data[c2]])
clust_centers

[array([0.40833394, 0.15426176, 0.28525938]),
 array([0.89069681, 0.69531012, 0.06547386])]

In [4]:
# el np.vstack lo pongo para poner un punto encima del otro, pero es lo mismo
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.40833394, 0.15426176, 0.28525938],
       [0.89069681, 0.69531012, 0.06547386]])

In [ ]:
# ya tenemos los dos baricentros c1 y c2:

In [6]:
from scipy.cluster.vq import vq

In [7]:
clusters = vq(data, clust_centers)
clusters

(array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 0], dtype=int32),
 array([0.74420006, 0.36728703, 0.79431691, 0.86623535, 0.41961508,
        0.24555053, 0.25734861, 0.27996917, 0.28122634, 0.        ,
        0.61102533, 0.48939932, 0.46569978, 0.51332358, 0.507706  ,
        0.36975073, 0.41465689, 0.63319059, 0.31186759, 0.56817402,
        0.98801503, 0.90327063, 0.40347365, 0.93072369, 0.        ,
        0.69248147, 0.09787121, 0.28872916, 0.58316953, 0.59573214]))

In [ ]:
# el primer array nos da la información de qué puntos pertenecen a cada cluster
# el segundo array nos da la distancia de cada una de las 30 observaciones del baricentro del clustering final. es decir, cada numero representa la distancia de ese punto al baricentro del cluster que indique el primer array

In [13]:
labels = clusters[0]
labels

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0], dtype=int32)

In [8]:
!pip install chart_studio
import chart_studio.plotly as py
import plotly.graph_objects as go 
import plotly.graph_objects as go
import plotly.offline as ply

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 5.1 MB/s eta 0:00:00


In [ ]:
# esto no sé porqué lo ha puesto...

In [21]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)

ply.plot(fig, filename='Clusters.html')
ply.plot(fig)

'temp-plot.html'

In [ ]:
# tambien podemos usar esto de abajo y nos da los dos baricentros

In [9]:
from scipy.cluster.vq import kmeans

In [10]:
kmeans(data, clust_centers)

(array([[0.33187269, 0.39226684, 0.51731162],
        [0.79253833, 0.6534306 , 0.37082358]]),
 0.40973035803436414)

In [ ]:
# arriba han salido los dos baricentros
# el ultimo número es la suma de los cuadrados de los errores normalizado

In [ ]:
# y tambien podemos usar esto de abajo y nos da tambien los baricentros

In [11]:
kmeans(data, 2)

(array([[0.43742227, 0.41167451, 0.79774268],
        [0.51743166, 0.52441937, 0.24897534]]),
 0.3971249136282671)